Repository lightningdevkit/rust-lightning, pull requests merged in 2020-05, with the labels that each got.

#613 Make channel reserve variable names less confusing.
  lightning/src/ln/channel.rs
  lightning/src/ln/functional_tests.rs
Labels: Easy to Review

#539 Require static_remotekey
  fuzz/src/full_stack.rs
  lightning/src/chain/keysinterface.rs
  lightning/src/ln/chan_utils.rs
  lightning/src/ln/channel.rs
  lightning/src/ln/channelmanager.rs
  lightning/src/ln/channelmonitor.rs
  lightning/src/ln/features.rs
  lightning/src/ln/functional_tests.rs
  lightning/src/ln/msgs.rs
  lightning/src/ln/peer_handler.rs
  lightning/src/util/enforcing_trait_impls.rs
Labels: High Review Priority, Moderate Review Difficulty

#624 Extract encode_and_send_msg into a method.
  lightning/src/ln/peer_handler.rs
Labels: Easy to Review

#610 Move back to ChannelMonitor RemoteTxCache
  fuzz/src/chanmon_consistency.rs
  fuzz/src/full_stack.rs
  lightning/src/chain/keysinterface.rs
  lightning/src/ln/chan_utils.rs
  lightning/src/ln/channel.rs
  lightning/src/ln/channelmonitor.rs
  lightning/src/ln/functional_tests.rs
  lightning/src/ln/onchaintx.rs
  lightning/src/util/enforcing_trait_impls.rs
  lightning/src/util/macro_logger.rs
  lightning/src/util/test_utils.rs
Labels: Hard to Review, High Review Priority

#620 Pre-C Bindings Cleanup
  fuzz/src/chanmon_consistency.rs
  fuzz/src/full_stack.rs
  lightning-net-tokio/src/lib.rs
  lightning/src/chain/keysinterface.rs
  lightning/src/chain/transaction.rs
  lightning/src/ln/chan_utils.rs
  lightning/src/ln/channel.rs
  lightning/src/ln/channelmanager.rs
  lightning/src/ln/channelmonitor.rs
  lightning/src/ln/functional_test_utils.rs
  lightning/src/ln/functional_tests.rs
  lightning/src/ln/peer_handler.rs
  lightning/src/util/macro_logger.rs
  lightning/src/util/test_utils.rs
Labels: Moderate Review Difficulty
