Repository lightningdevkit/rust-lightning, pull requests merged in 2022-02, with the labels that each got.

#1268 Include inbound-claimed-HTLCs in reported channel balances
  lightning/src/ln/channel.rs
  lightning/src/ln/functional_tests.rs
Labels: fuzzer fix

#1199 Add support for multi-node receive
  fuzz/src/chanmon_consistency.rs
  fuzz/src/full_stack.rs
  lightning-background-processor/src/lib.rs
  lightning-invoice/src/lib.rs
  lightning-invoice/src/utils.rs
  lightning/src/chain/keysinterface.rs
  lightning/src/ln/channel.rs
  lightning/src/ln/channelmanager.rs
  lightning/src/ln/functional_test_utils.rs
  lightning/src/ln/onion_utils.rs
  lightning/src/ln/peer_channel_encryptor.rs
  lightning/src/util/crypto.rs
  lightning/src/util/mod.rs
  lightning/src/util/scid_utils.rs
  lightning/src/util/test_utils.rs
Labels: Seeking Code Review, Optech Make Me Famous

#1266 Fix a debug panic caused by receiving MPP parts after a failure
  lightning/src/ln/channelmanager.rs
  lightning/src/ln/functional_tests.rs
Labels: fuzzer fix

#1316 Drop `fuzztarget` feature entirely
  fuzz/Cargo.toml
  fuzz/src/bin/chanmon_consistency_target.rs
  fuzz/src/bin/chanmon_deser_target.rs
  fuzz/src/bin/full_stack_target.rs
  fuzz/src/bin/msg_accept_channel_target.rs
  fuzz/src/bin/msg_announcement_signatures_target.rs
  fuzz/src/bin/msg_channel_announcement_target.rs
  fuzz/src/bin/msg_channel_reestablish_target.rs
  fuzz/src/bin/msg_channel_update_target.rs
  fuzz/src/bin/msg_closing_signed_target.rs
  fuzz/src/bin/msg_commitment_signed_target.rs
  fuzz/src/bin/msg_decoded_onion_error_packet_target.rs
  fuzz/src/bin/msg_error_message_target.rs
  fuzz/src/bin/msg_funding_created_target.rs
  fuzz/src/bin/msg_funding_locked_target.rs
  fuzz/src/bin/msg_funding_signed_target.rs
  fuzz/src/bin/msg_gossip_timestamp_filter_target.rs
  fuzz/src/bin/msg_init_target.rs
  fuzz/src/bin/msg_node_announcement_target.rs
  fuzz/src/bin/msg_onion_hop_data_target.rs
  fuzz/src/bin/msg_open_channel_target.rs
  fuzz/src/bin/msg_ping_target.rs
  fuzz/src/bin/msg_pong_target.rs
  fuzz/src/bin/msg_query_channel_range_target.rs
  fuzz/src/bin/msg_query_short_channel_ids_target.rs
  fuzz/src/bin/msg_reply_channel_range_target.rs
  fuzz/src/bin/msg_reply_short_channel_ids_end_target.rs
  fuzz/src/bin/msg_revoke_and_ack_target.rs
  fuzz/src/bin/msg_shutdown_target.rs
  fuzz/src/bin/msg_update_add_htlc_target.rs
  fuzz/src/bin/msg_update_fail_htlc_target.rs
  fuzz/src/bin/msg_update_fail_malformed_htlc_target.rs
  fuzz/src/bin/msg_update_fee_target.rs
  fuzz/src/bin/msg_update_fulfill_htlc_target.rs
  fuzz/src/bin/peer_crypt_target.rs
  fuzz/src/bin/router_target.rs
  fuzz/src/bin/target_template.txt
  fuzz/src/bin/zbase32_target.rs
  lightning-invoice/fuzz/Cargo.toml
  lightning/Cargo.toml
  lightning/src/chain/chainmonitor.rs
  lightning/src/chain/channelmonitor.rs
  lightning/src/lib.rs
  lightning/src/ln/chan_utils.rs
  lightning/src/ln/channel.rs
  lightning/src/ln/channelmanager.rs
  lightning/src/ln/mod.rs
  lightning/src/ln/msgs.rs
  lightning/src/routing/router.rs
  lightning/src/util/chacha20.rs
  lightning/src/util/chacha20poly1305rfc.rs
  lightning/src/util/fuzz_wrappers.rs
  lightning/src/util/mod.rs
Labels: Seeking Code Review

#1303 Generate docs with features for docs.rs
  lightning-background-processor/Cargo.toml
  lightning-background-processor/src/lib.rs
  lightning-block-sync/Cargo.toml
  lightning-block-sync/src/convert.rs
  lightning-block-sync/src/lib.rs
  lightning-invoice/Cargo.toml
  lightning-invoice/src/lib.rs
  lightning-net-tokio/Cargo.toml
  lightning-net-tokio/src/lib.rs
  lightning-persister/Cargo.toml
  lightning-persister/src/lib.rs
  lightning/Cargo.toml
  lightning/src/lib.rs
  lightning/src/routing/scoring.rs
  lightning/src/util/events.rs
Labels: Seeking Code Review

#1327 Log more during ChannelMonitor updating
  lightning/src/chain/channelmonitor.rs
Labels: Seeking Code Review
